# Site settings
title: Mallikarjun Tirlapur
email: tirlapurmallikarjun@gmail.com
phone: "+919740003234"
description: > # this means to ignore newlines until "baseurl:"
  Senior Staff Embedded Software Developer with expertise in Java Card Operating Systems 
  and secure embedded solutions. 14+ years of experience in embedded software development, 
  team leadership, and innovation with 3 filed patents.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mallikarjuntirlapur.github.io" # the base hostname & protocol for your site
github_username: MallikarjunTirlapur
linkedin_username: mallikarjun-tirlapur

# Personal info
name: Mallikarjun Tirlapur
tagline: Senior Staff Embedded Software Developer
location: "#28, 1st B Main Road, Mohan Kumar Nagar, Yeshwanthpur, 560022, Bengaluru, India"
company: Infineon Technologies AG

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/